// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConnectedSnippetIDs(arg1) {
  return window['go']['main']['App']['GetConnectedSnippetIDs'](arg1);
}

export function GetFileCode(arg1) {
  return window['go']['main']['App']['GetFileCode'](arg1);
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetFiles() {
  return window['go']['main']['App']['GetFiles']();
}

export function GetSnippetAssembly(arg1) {
  return window['go']['main']['App']['GetSnippetAssembly'](arg1);
}

export function GetWikilinkColor(arg1, arg2) {
  return window['go']['main']['App']['GetWikilinkColor'](arg1, arg2);
}

export function GetWikilinkEdges(arg1, arg2) {
  return window['go']['main']['App']['GetWikilinkEdges'](arg1, arg2);
}

export function SetWikilinkColor(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetWikilinkColor'](arg1, arg2, arg3);
}
