// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConnectedSnippetIDs(arg1:string):Promise<Array<string>>;

export function GetFileCode(arg1:string):Promise<string>;

export function GetFileInfo(arg1:string):Promise<main.FileInfoView>;

export function GetFiles():Promise<Array<main.FileNode>>;

export function GetSnippetAssembly(arg1:string):Promise<Array<main.SnippetView>>;

export function GetWikilinkColor(arg1:string,arg2:string):Promise<string>;

export function GetWikilinkEdges(arg1:string,arg2:string):Promise<Array<main.WikilinkEdgeInfo>>;

export function SetWikilinkColor(arg1:string,arg2:string,arg3:string):Promise<void>;
